### ISSUE TITLE
Как использовать

### ISSUE THREAD

**Issue by oksibutch** [WhiteApfel/keyrt#1]
Добрый день могли бы вы написать как подружить ваш код например с node red или home assistant? И второй вопрос как получить токен в приложении ключ

**Comment by WhiteApfel** [comment]
Вопросами других продуктов бесплатно не занимаюсь.

Ключ через mitm можно вытащить из приложения, либо авторизоваться заново с помощью методов https://github.com/WhiteApfel/keyrt/blob/master/keyrt/aioclient.py#L149C5-L180C31
